# Base stage
FROM node:20.11-alpine
WORKDIR /app

COPY package*.json ./

ENV NODE_ENV=development
RUN npm install

COPY prisma ./prisma/
RUN npx prisma generate

COPY . .

EXPOSE 3000
ENTRYPOINT ["npm", "run", "watch"]
